### PR TITLE
Making LIT use normal python as per Stephen McCamant's suggestion

### PR DESCRIPTION
**Pull request by msoos**
Diff as per issue #88

### CODE REVIEW

**Comment by msoos** [comment]
@smcc Can you please comment on whether you still need this? Maybe I can fix something around the underlying issue such that it doesn't break the build.

**Comment by smcc** [comment]
I don't know that my relationship with this change has ever been as strong as "need". I do spend a larger than usual amount of time trying to get STP to run compiling entirely from source without installing anything in /usr, because of the centralized systems administration system our department has, but I'm aware that most other users are not in that situation any more.

My thinking when I made this change was that it would make the build process strictly more flexible, and it was motivated by a particular build environment that seemed to me like it should work. On the other hand Dan's opinion was that the configuration I was trying was not supposed to work and would not be worth supporting. I haven't been won over by his argument but lots of trade-offs like this have to be made in supporting a build process so my opinions probably shouldn't stand in the way of progress.

I believe that even within my limitations of not installing things in /usr, there are different configurations of the other tools that would allow me to build a vanilla STP correctly without this change. And since for now I'm already using a branched (and currently somewhat out of date) version of STP with FuzzBALL, no trunk changes will have any immediate effects on FuzzBALL users.

Understanding why this change breaks the Travis build might lead to an insight and a different way of making the change that would make everyone happy; it seems to clearly be some kind of counterexample to my earlier thought that the change would not break any builds. However in a minute or so of looking I couldn't understand what the problem was from the Travis reports that are linked to this pull request. Is it obvious to you which of the lines in the log represents the build failure?

**Comment by msoos** [comment]
I suspect the build failure to be something entirely different. As for flexibility of the build system -- you are probably right on that. The python to be used should probably be optionally passable to the `cmake`. I don't have the environment to check that though. If you can create a diff for that to cmake it would be great.

As for drift of versions, I'm sorry to hear. I should work more on STP so it would make more sense to keep it updated inside projects. There have been some diffs and fixes over the months, but nothing major :( I have a lot of commitments, and I have been improving CryptoMiniSat in significant ways...

**Comment by delcypher** [comment]
> The python to be used should probably be optionally passable to the cmake

Changing the value of (hidden by default) of ``PYTHON_EXECUTABLE`` in the cache will let you do this.

**Comment by msoos** [comment]
Oh wow, let me make that explicit then. The commit https://github.com/stp/stp/commit/3785148da15919de445e476a6f20b06c881cf50c now fixes this issue. Thanks for everyone for their input!

**Pull request closed without merging**
