### PR TITLE
Adding an API routine to allow for obtaining a BV as a bit string

### PR DESCRIPTION
**Pull request by andrewvaughanj**
## Issue

#357 requested the ability to obtain a bit string from a given constant BV.

## Resolution

This PR adds an additional API call (`vc_printBVBitStringToBuffer`) that allows the user to obtain this representation.

As per the doc-string, the "output parameter" pointer *belong to the callee*.

Test added: `tests/api/C/bit_string.cpp`.

Signed-off-by: Andrew V. Jones <andrew.jones@vector.com>

### CODE REVIEW

**Comment by andrewvaughanj** [comment]
Travis is sad due to #359

**Comment by rgov** [comment]
I'm not opposed to this but is it preferable to get this out as an ASCII string rather than some other sort of bignum representation? I guess this saves us the hassle of needing to choose a bignum library to make part of the interface.

**Comment by andrewvaughanj** [comment]
That is how it is implemented; it returns an ASCII `char*` for the bit string.

**Comment by rgov** [comment]
Right, I'm just saying that format is somewhat of a computational dead end without a bignum library that then parses it back into machine representation.

Just noticing that OpenSSL's `BN_bin2bn` doesn't parse binary strings, so that's out. GMP seems to have `mpz_set_str` which accepts whatever base.

**Comment by andrewvaughanj** [comment]
Ah! Gotcha! Sure, I'm not sure why the user wants this, but I would guess it is because they have some parsing already for what Boolector returns ([the `.assignment` will be a bit string](https://boolector.github.io/docs/pyboolector.html)).

**Comment by andrewvaughanj** [comment]
Probably this is a better reference [`const char *boolector_bv_assignment(Btor *btor, BoolectorNode *node)`](https://boolector.github.io/docs/cboolector_index.html):

> Returns
>
> String representing a satisfying assignment to bit-vector variables and a consistent assignment for arbitrary bit-vector expressions. The string representation will use binary [...]
>

**Comment by mikhailramalho** [comment]
I was asking if we could get a binary string because it seems consistent with your C API; there is a method `vc_bvConstExprFromStr` that creates a bit-vector from a binary string after all.

I don't really mind using gmp, but it seems a bit of an overkill to add it as dependency only because of this function. We have our own bigint library in our tool, which converts to and from binary strings.

**Comment by msoos** [comment]
I think this is a fine setup, and looking through the code, it all makes sense. No need to explicitly take a bignum library, the user can do it themselves quite easily I think :) Merging!

**Pull request merged**
