### PR TITLE
Remove author attribution in file headers

### PR DESCRIPTION
**Pull request by rgov**
This change removes author attribution from the tops of files. The intention is not to deny anyone recognition for the work, but I will let this sit for a little bit to see if anyone feels differently.

* The `AUTHORS` file remains and contributors are invited to add themselves to it. (It does need an update.)

* The git log already details exactly who contributed what to which file.

* We no longer have to keep the file headers up-to-date, or feel compelled to add attribution every time a change is made.

* The headers are not particularly accurate. Many were bulk-added to include me (or my alter ego, Ryan Gvostes), even though I'm sure I did not modify most of those files; other contributors whose names deserve to be up there are not.

Thoughts?

### CODE REVIEW

**Comment by rgov** [comment]
I am also happy to remove the "begin date" in the headers which doesn't serve much use. The earliest commit imported into GitHub is from 2008 and some of the headers do go back further to 2005. But it is mostly a point of historical curiosity than useful information in the source file. The git log provides much richer information here as well.

**Comment by msoos** [comment]
These were added because someone who was using STP was very adamant about them. I don't remember exactly who it was, but it seemed really important for them. Ah, I found it, here:

https://github.com/stp/stp/issues/199

For Debian apparently. Debian takes copyright super-seriously so it makes sense. Please check that before changing authors. Looks pretty serious.

**Comment by rgov** [comment]
Eh ok. I have never heard of another project that requires a list of authors in every header, ever. I am pretty sure 90% of the projects in Debian do not do this. LLVM does not, for example. I would be fine with a general "(c) STP contributors, see AUTHORS file" if we really need it.

I can understand the issue described in #199 where the `AUTHORS` file / `LICENSE` file did not match up with some headers we imported from other projects, as we've recently discussed. I also can understand that that could spook Debian, if it seems like the project is claiming credit for other peoples' work.

A copy of the license or a reference to the license file is common. This way contributors understand their modifications are licensed under the project license. Some projects require signing a Contributor License Agreement before a pull request will be accepted, which basically just makes me confirm I understand that the project uses an open source license. There are GitHub bots for that, if we want.

**Comment by msoos** [comment]
Sure, what you said makes 100÷ sense. Just wanted to point out that those
authors were there for a particular reason. Let's merge this PR but make
sure we don't upset Debian and other projects that care about about
authorship in the meanwhile :)

**Comment by andrewvaughanj** [comment]
So Michael Tautschnig is a prominent Debian contributor https://qa.debian.org/developer.php?login=mt@debian.org and packages CBMC for Debian -- however, even *he* has commits against CBMC that do an adhere to that rule: https://github.com/diffblue/cbmc/blob/develop/src/util/allocate_objects.cpp (file chosen totally at random).

**Comment by hellovijay** [comment]
Hi Ryan,

I would be opposed to this change. I am the one who started the STP project
and wrote most of STP's code from 2005 till around 2012 (or thereabouts).
Since then Trevor, Mate, yourself, and others have also contributed and
extended the solver in many ways.

1) I think the change you are suggesting would diminish my contribution to
the tool (that I developed as part of my PhD and maintained for several
years). I would imagine others who have contributed would have a similar
opinion. What is wrong with allowing everyone who has contributed to a file
in STP's source code to add their names to the file header they contributed
to? It is up to each author to make sure that their contributions get
recognized in this way. This seems fair to me.

2) In addition, they can add their names to the AUTHORS file as well.

3) Finally, I am happy to relinquish my copyright to some kind of "STP
maintainers list" entity.

I don't understand the motivation for proposing this change. Can you please
clarify?

Cheers,
Vijay Ganesh.

**Comment by rgov** [comment]
@hellovijay Understood. This pull request won't go forward if you are not satisfied.

Note that you are listed as the first author in the AUTHORS file and I believe you should remain there.

The reasons for suggesting the removal are highlighted in my original post, such as having poor consistency throughout the project. A changelog / author block at the top of source files is uncommon nowadays with version control that tracks this information much better.

The issue came to mind as @andrewvaughanj is contributing to many files and the author list in each file will grow longer. Also my name is spelled wrong in almost every file :)

Perhaps this would be better:

```
(c) 2005-2008 Vijay Ganesh [or however you please]
(c) 2005- STP contributors (see AUTHORS file)
```

**Comment by rgov** [comment]
>>> What is wrong with allowing everyone who has contributed to a file in STP's source code to add their names to the file header they contributed to? It is up to each author to make sure that their contributions get recognized in this way. This seems fair to me.

There's certainly nothing wrong with this, but note that this information is already in the git history and surfaced in the GitHub website (see the avatars across the top [on this page](https://github.com/stp/stp/blob/master/lib/CMakeLists.txt) for example).

Appending a name to the list though doesn't convey how much that person contributed. For example, I wouldn't want to put my name on a file that you wrote the vast majority of simply because I fixed a small bug.

**Comment by rgov** [comment]
Sorry to triple-post, but in the [example file](https://github.com/stp/stp/blob/master/lib/CMakeLists.txt) I linked to in the previous message, note there are 3 people credited for the file (including me, who did not contribute to that file), while there are 5 other contributors who are not credited. This is why it is a bit of a mess.

**Comment by hellovijay** [comment]
Okay.

* How about the person who originates a file gets to put their name at the
top. The term AUTHORS is replaced by "FIRST AUTHORS".

* Please do feel free to correct the spelling of your name where it
appears.

* With regard to copyright, I am comfortable with the following:

(c) 2005-2015    Vijay Ganesh, David L. Dill

(c) 2015-2020    Vijay Ganesh, David L. Dill, Mate Soos

(c) 2020-present STP contributors (see AUTHORS file)

Let me know if the above approach works for you.

**Comment by andrewvaughanj** [comment]
## On the overall copyright

I have a few contributions here and there to STP, and nowhere near the number of that of Trevor/Dan/Mate, however I feel that this:

```
(c) 2015-2020    Vijay Ganesh, David L. Dill, Mate Soos
```

Is a bit disingenuous to the other major contributors to STP during that five year window (especially people like Trevor and Dan). I've omitted Ryan here, because if I'm not careful, we'll end-up with an ever growing list, and I'm bound to forget someone ... so I'll start as I mean to go! Sorry, Ryan 😬 

Anyway, in 2015, and on #199 you wrote:

> I am quite happy to share the copyright. STP wouldn't be where it is without
> the contributions of Trevor, Mate, Dew, Ryan, Dill, Khoo, and others.
> 
> If I were to highlight the most important contributors, I would say they
> would be myself, Trevor Hansen, Mate Soos, and David L. Dill.
> 

If we're agreeable, could we just retroactively assign the copyright to the maintainers starting in 2015 (which you and David would be one of)? That way, no-one's nose gets out of shape.

We can just ensure that the current AUTHORS file lists everyone who has contributed _at all_, but make it clear that between 2005 and 2015, the copyright was the sole ownership of Vijay Ganesh and David L. Dill.

Was there actually an official assignment of copyright of STP to Mate during that window? If we're retroactively assigning copyright to Mate, I would vote for retroactively assigning copyright to the "STP maintainers" (whoever they may be).


## On 'Author' vs. 'Original Author'

I actually think the idea of "original author" is *worse* -- what happens if someone rewrites 99% of the file (but, say, leaves the header block + doesn't actually change the API); does that really mean that the original author applies here, and that the new contributor feels they can't add their name because they are not the "original author"?


## When to update the copyright block

We also need to juggle Ryan's point about when you add copyright to the top of a file (I know that Mate and I had this with CMS, and Mate rightly removed me when I naively added myself thinking I was "doing the right thing").

Even if someone makes a 10 line change in a 1000 line file, surely they do actually retain "artistic copyright" over those 10 lines? The question we need to decide if that is enough to put the name at the top of the file.


## Personal view

My personal view is that we should strip all of these copyrights (mainly because they're wrong in a lot of places, which is arguably _even worse_), ensure we maintain an up-to-date AUTHORS file and then require [DCO](https://github.com/apps/dco) + squashed and signed-off commits (the same approach as Boolector and CVC4) for contributions going forwards.

This means that it is clear that anyone contributing to STP has assigned their copyright over to the STP project *and* that they have the authority to do so.

In case it helps, here is CVC4's guide to contributing: https://github.com/CVC4/CVC4/blob/master/CONTRIBUTING.md

**Comment by hellovijay** [comment]
Hi Andrew,

On the overall copyright
I agree with you.

I didn't mean to diminish the contributions of others and I clearly didn't
contribute any code in the time period from 2015-2020. That must have been
an oversight on my part in my previous email. Sorry about that. Feel free
to change it the following:

(c) 2015-2020 Trevor Hansen, Mate Soos, Ryan, Andrew,...

Further, I agree with the rest of your points in your email under the
heading "On the Overall Copyright".

I am fine with the CVC4 approach to copyright you mentioned.
On 'Author' vs. 'Original Author'
I don't think any of the proposed solutions are ideal. I really don't know
how to resolve this one.

Cheers,
Vijay Ganesh.

**Comment by TrevorHansen** [comment]
I feel like we should be able to agree on some of these changes.  As a start, can anyone see issues if we:
* As @rgov mentioned, remove the "begin date" from files.
* Have some bot (or something) to confirm with contributors (before applying their patches) that they know STP is MIT licensed.
* Fix the spelling of contributors names.

**Comment by andrewvaughanj** [comment]
## Authors

I (genuinely) think the best way to resolve this issue is to drop the `authors` bit from the top of each file and do this:

1. If the file existed *before* 2015, then we add `(c) 2005-2015 Vijay Ganesh, David L. Dill`

2. If the file has been changed *after* 2015, the new add `(c) 2015-present STP contributors (see AUTHORS file)`

I'm actually fine to have a more sweeping change that just does 1. in *every* file (irrespective of its genus, apart from the `ext` files) and 2. as above.

If we do this, then we just need to make sure that Ryan's name is spelled correctly *in the `AUTHORS` file*.

After doing this everyone appears in the `git log` and in the `AUTHORS` file, and we have no issues going forward.


## Begin date

Remove it ✅ 


## Copyright agreement

I'm happy to take this as a separate action not as part of this PR -- I will set up DCO + write a contributors guide (and see if we can have a GitHub Action that confirms commits are signed-off).

**Comment by hellovijay** [comment]
I like Andrew's idea.

-Vijay.

**Comment by TrevorHansen** [comment]
> I (genuinely) think the best way to resolve this issue is to drop the authors bit from the top of each file and do this:
>     If the file existed before 2015, then we add (c) 2005-2015 Vijay Ganesh, David L. Dill
>     If the file has been changed after 2015, we add (c) 2015-present STP contributors (see AUTHORS file)

I don't think it's reasonable to transfer copyright over from other contributors to Vijay and David without the other contributor's permission. In the past some contributors have insisted on maintaining their copyright. 

Transferring copyright to David L. Dill seems a bit weird to me, too. Was his last contribution really in 2015?

To sort this out, I suspect we're going to need something more nuanced.

**Comment by andrewvaughanj** [comment]
> I don't think it's reasonable to transfer copyright over from other contributors to Vijay and David without the other contributor's permission. In the past some contributors have insisted on maintaining their copyright.
>

Okay, maybe it should just be all files that existed before 2015 get Vijay+David, and any file that was changed by anyone else (ever!) gets STP contributors (and the year it was first changed by someone who wasn't Vijay+David)?

**Comment by msoos** [comment]
I agree with Trevor here. For example, my first commit is from 2009 and so is Trevor's. Here is some food for thought:

```
$ git log | grep "Author:" | sed "s/Author: //" | sed "s/<.*//" | sort | uniq -c | sort -n
      1 Artur Dmowski 
      1 Cristian Cadar 
      1 Gleb Popov 
      1 John Regehr 
      1 Jonas Zaddach 
      1 Li-yao Xia 
      1 Lukas Prokop 
      1 Marek Chalupa 
      1 Ondřej Súkup 
      1 Philip Guo 
      1 Raphael Michel 
      1 Reini Urban 
      1 Samuel Neves 
      1 sneves 
      1 Will Glynn 
      2 Jonas Wagner 
      2 Max Zinkus 
      2 petercol 
      2 Xi Wang 
      3 Andrew Chi 
      3 Austin Clements 
      3 Carsten Sinz 
      3 Jerry James 
      3 junhee cho 
      3 Martin Nowack 
      3 TrevorHansen 
      3 vganesh2013 
      4 Alexander Jesner 
      5 Stephan Falke 
      6 Robbepop 
      7 Brian Foley 
      7 Jiri Slaby 
      8 Edward J. Schwartz 
      8 Matt Arsenault 
     10 Michael Katelman 
     15 Trevor hansen 
     17 Florian Merz 
     20 Stephen McCamant 
     22 Norbert Manthey 
     29 Jurriaan Bremer 
     29 Khoo Yit Phang 
     38 Felix Kutzner 
     54 Andrew V. Jones 
     66 Ryan Govostes 
    176 Dan Liew 
    272 Vijay Ganesh 
   1045 Mate Soos 
   1088 Trevor Hansen 
```

Note that number of commits is *not* equivalent to the *amount of work*. In particular, often the starting of a project is already a *substantial* amount of work without any commits. But it does show that a lot of people contributed to the project. 

Between project inception to 2014 (inclusive) we have:
```
      1 Artur Dmowski 
      1 John Regehr 
      1 Jonas Zaddach 
      1 Philip Guo 
      1 Raphael Michel 
      1 Reini Urban 
      1 Samuel Neves 
      1 sneves 
      1 Will Glynn 
      2 Jerry James 
      2 Jonas Wagner 
      2 petercol 
      2 Xi Wang 
      3 junhee cho 
      3 vganesh2013 
      4 Alexander Jesner 
      5 Stephan Falke 
      8 Edward J. Schwartz 
      8 Matt Arsenault 
     10 Michael Katelman 
     17 Florian Merz 
     20 Stephen McCamant 
     29 Jurriaan Bremer 
     29 Khoo Yit Phang 
     31 Ryan Govostes 
    154 Dan Liew 
    271 Vijay Ganesh 
    272 Mate Soos 
    912 Trevor Hansen 
```

Sorry for going for the data-driven approach :) Again, there is lots of work that does not show in the logs. Another example is the work that goes into responding to customer queries and aligning within the team. None of these are trivial work and they don't (or barely) show up in the the above data.

Just my 2 cents :)

**Comment by rgov** [comment]
Perhaps we are overthinking this. We can have overlapping copyright assignments, see for instance OpenCV: https://github.com/opencv/opencv/blob/master/LICENSE

```
Copyright (C) 2000-2020, Intel Corporation, all rights reserved.
Copyright (C) 2009-2011, Willow Garage Inc., all rights reserved.
Copyright (C) 2009-2016, NVIDIA Corporation, all rights reserved.
Copyright (C) 2010-2013, Advanced Micro Devices, Inc., all rights reserved.
Copyright (C) 2015-2016, OpenCV Foundation, all rights reserved.
Copyright (C) 2015-2016, Itseez Inc., all rights reserved.
Copyright (C) 2019-2020, Xperience AI, all rights reserved.
```

**Comment by hellovijay** [comment]
Hi All,

I am positive you will come up with a fair way to resolve this issue. I
like the idea that Ryan sent in his last email, with overlapping copyrights.

Thanks for your wonderful work!

Cheers,
Vijay Ganesh.

**Comment by andrewvaughanj** [comment]
I've been trying to make a more polished attempt to process the commit history; I wrote a script here:

https://github.com/andrewvaughanj/parse_stp_history/blob/master/parse_stp_history.py

This script walks all commits from the start of the repo and tracks adds/deletes/renames. Importantly, the files that are part of the initial commit are marked as owned by Vija and David, *and not* by Michael Katelman.

Here are the current statistics:

- We have 541 files in total

- There are 28 files that have only ever been touched by Vijay (and therefore are also owned by David); these are mostly .cvc files

- There are 119 files that have been directly modified by Vijay *and other people*

- There are 312 files that existed *before* `Fri Sep 18 00:14:22 2015 -0400` (the date of Vijay's last commit), but for which Vijay did not directly commit to (it is hard to say which of these don't have "inherited" copyright)

- There are 82 files that were created *after* `Fri Sep 18 00:14:22 2015 -0400`

You can find the complete output here:

https://github.com/andrewvaughanj/parse_stp_history/blob/master/stp_history.txt

My suggestion here is:

- The 28 exclusive files get `(c) 2005-2015 Vijay Ganesh and David L. Dill`

- The 119+312 "mixed" files get `(c) 2005-2015 Vijay Ganesh and David L. Dill` and `(c) 2008-2020 STP contributors`

- The 82 exclusively STP files get `(c) 2008-2020 STP contributors`

Does this seem reasonable to everyone?

**Pull request closed without merging**
