### PR TITLE
DLL building on Windows and C interface symbol visibility

### PR DESCRIPTION
**Pull request by fkutzner**
This PR enables DLL building on Windows (see the discussion in #247).

To get the tests running, some adjustments in the CMake files were unavoidable - namely, generating files depending on which configuration (Debug, Release, ...) is used when invoking MSBuild, since output directory of binaries depends on the configuration. This is done with generator expressions, for which CMake 3.0.2 is needed.

I originally made most of the CMake changes in https://github.com/fkutzner/stp/tree/win64dll (where all symbols get exported from DLLs) and ported them into this branch. In win64dll, the tests ran fine, however with this branch, the query-file-tests seem to hang. On the other branch, I needed to increase the EXE stack size limit for the query-file-tests.

I've also deactivated boost in AppVeyor for now. stp_simple can be built, but stp cannot, since two different versions of the debugging database stp.pdb are generated - one for the DLL, another one for the EXE, causing the linker to refuse linking the executable.

To make sure I didn't inadvertently break anything, I've compiled and tested STP on macOS. It runs fine :)

Hope you like the PR :)

### CODE REVIEW

**Comment by msoos** [comment]
Wow, amazing work, thanks! I'll let the builds finish. There have been a number of issues with builds lately, so it will fail, but I want to see how it fails :) Your fixes _really_ bring Windows right back, I mean tests working is completely crazy amazing. Well done! Fingers crossed :)

The boost thingy is an issue, I love boost and it should work. We'll fix that one later. It really is pretty close to working, and I managed to make it work more than once.

**Comment by fkutzner** [comment]
Thanks :) Boost and tests are on my todo list. Boost should be easy - on my machine, it was really just the linker refusing to write an stp.pdb file (for the exe) when taking a an stp.pdb in the same directory (the dll .pdb) as an argument. The hanging tests may be some weird DLL problem. But I'm optimistic, since the tests passed with the all-symbol-exporting DLL.

**Comment by fkutzner** [comment]
There's another thing about running the tests, which I forgot to mention: the _not_ program needs to be in %PATH%. I've installed one in my Windows directory, but it should be pretty easy to add a small _not_ implementation to STP.

**Comment by msoos** [comment]
Oh, weird. Where do we call it? By the way, I just fixed all the tests so they should compile statically too, at least on Linux. I'm a bit confused about Windows and DLLs and Windows testing. I'm looking forward to you working on it when you have time :) It's going quite well now, we have moved to an upgraded Linux, fixed a bunch of issues related to dynamic and static linking, etc. It's a whole lot better now. Thanks for the lots and lots of contributions! :)

**Comment by fkutzner** [comment]
IIRC the lit tool calls _not_. I'll try to get the tests to run in AppVeyor later this week and then tackle the other issues.

**Comment by msoos** [comment]
Yeah, sorry, I kinda broke python for the moment on Windows. I'm trying to fix it. It's slightly complicated... The `file(GENERATE OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>/stp.py` broke the Linux build, but I see how the `$<CONFIG>` is needed in Windows. Without the $<CONFIG> it works in Linux, but that breaks Windows, and vice-versa. So I'm trying to fix it back :) I'll let you know when it's fixed.

**Comment by fkutzner** [comment]
No problem, thanks for fixing it :) I probably won't be able to commit much in the next few days, but that's not related to the current AppVeyor issues. They're curious, I cherry-picked the python-binding commit from https://github.com/fkutzner/stp/commits/win64dll and that branch passed Travis. I only had to configure Travis to use a more recent CMake version (>= 3.0.2), but that was the old setup anyway. Building it on macOS also didn't cause any trouble. I'm using CMake 3.8.0 on Windows and 3.7.2 on macOS.

**Pull request merged**
