### PR TITLE
Mergesat

### PR DESCRIPTION
**Pull request by conp-solutions**
This series adds MergeSat as another SAT backend. During working on it, I noticed that instead of just adding MergeSat, I could have actually implemented a compile-time replacement strategy for MiniSat.

As I currently only wanted to integrate MergeSat, I'll leave the other task open for now.

This series has not been tested extensively.

This is related to https://github.com/stp/stp/issues/349

### CODE REVIEW

**Comment by conp-solutions** [comment]
The Travis checks fail with an error that is hard to understand given the current output. Interestingly, it does not seem to fail for Riss, alghouth Riss uses almost the same cmake and make invocation. Digging through this might take a while.

**Comment by andrewvaughanj** [comment]
@conp-solutions sorry if this is a silly question, but why are the Riss and MergeSat back-ends only compiled statically? We recently disabled static builds through Travis (as they didn't work).

I'd love to get your stuff moving along, but I'd like to *not* build it statically if possible. I have nothing against the static builds, there's just work to do in getting them reinstated, so I don't want to block your PRs because of that.

**Comment by conp-solutions** [comment]
There is no clear reason. I quickly managed to produce a static build, hence, i just used that. It might be possible to just drop the static keyword, I simply did not test that route, as static binaries have been the easier approach for the SMT competition.

Best,
Norbert

**Comment by andrewvaughanj** [comment]
@conp-solutions do you think we can split off https://github.com/stp/stp/pull/354/commits/8e4ff44e5bb3dac529b916918590b797721c9680 into a separate PR? I don't think you need this for this branch (as it seems this branch *only* has `#define MINISAT_NSPACE Minisat` in it).

Genuinely, I get the intent, but it makes it hard to see what's Mergesat related vs. that change. If it works like I believe it does, then it would be good to have a CMake option to set which solver to use for `MINISAT_NSPACE`.

**Comment by rgov** [comment]
This is a cool contribution but unfortunately it has since diverged from the codebase and would need some work to merge in.

@conp-solutions - do you still have interest in pursuing this?

**Comment by conp-solutions** [comment]
I currently have no further plans of pursuing this, thanks. Let me close this pull request.

**Pull request closed without merging**
